version: '3'
services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: refreshToken
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'
  adminer:
    image: adminer
    ports:
      - '8080:8080'
networks:
  default:
    driver: bridge
volumes:
  data: null